### ISSUE TITLE
I suggest to maintain this module for you from now on

### ISSUE THREAD

**Issue by edi9999** [peerigon/angular-expressions#10]
Hello @peerigon, 

you seem to not have time anymore to support this module, so I started a fork called bluerider : https://github.com/edi9999/bluerider

I published it under npm as `bluerider` and it contains all the latest change that are in master that were not released to `npm`

If you'd prefer, I can also become a contributor to angular-expressions and owner on the npm module, so that I can instead update this module instead of having to create a fork.

What do you think ?

**Comment by tangshuang** [comment]
Why dont you fork the repo and submit a pull request?

**Comment by edi9999** [comment]
Because this repository has no active maintainer.

**Comment by jhnns** [comment]
Hey @edi9999 👋, sorry for being unresponsive. Since we're not using this module in any of our products, it's hard to keep it maintained. I'm happy about everyone who wants to help out. According to your GitHub and Twitter profile, you're a decent person so I gave you push and publish rights 😁.

Please stick to semver and use your rights responsibly. People depend on this module in production. If you have any question or if there's something not working, write me an email.

Thanks again ❤️

**Comment by edi9999** [comment]
Thanks ! Can you also give me access to the npm module ?

**Comment by jhnns** [comment]
Yes, I've already done that:

![bildschirmfoto 2018-06-11 um 23 22 36](https://user-images.githubusercontent.com/781746/41257779-6186ef7a-6dce-11e8-8e69-43c0c00a1cb0.jpg)

**Comment by tangshuang** [comment]
Good news!
