### ISSUE TITLE
what version of angular is this based on?

### ISSUE THREAD

**Issue by Gooseus** [peerigon/angular-expressions#3]
What version of angular did you pull the Parse and Lexer from?

I'm not sure how much the expressions have changed with the versions, but it would be good to know which version of the syntax is supported if it does change.

**Comment by jhnns** [comment]
Yeah, I should have written down the revision number. I only know that [I've pulled the code on 12th March 2014](https://github.com/peerigon/angular-expressions/commit/e6c4983736611f62313cd9de42496695162c9a86).

I don't know about any big changes since then. I do know that they've removed legacy features, but I didn't pull those in the first place.

However, you're free to create a PR. Porting the code was quite easy :+1:

**Comment by edi9999** [comment]
From what I can see, the last update was on November 2016, so the related version of angular would be 1.6.0 which was released on 8th December 2016 : https://github.com/angular/angular.js/releases?after=v1.6.2
